# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b23b07b37c5f27be68e244e7c7cfc4c07dd82860beec584dad796a3958c518ebcfed3bd7a7f26d0a19b535a1dae256383b06b9eb0f4308a2ad112001b407261

test:
  secret_key_base: 53332cc02ea51a3e8ba0403cff2bf6717079ff9c2d4ecce846d08b7b74beef522492b589cc96288f788aa5796f267a8fade0c58fdf40635043c2d65686365763

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
